### ISSUE TITLE
Math Tex des neuen Jsons nicht kompatibel 

### ISSUE THREAD

**Issue by Konradrundfunk** [DARC-e-V/50ohm-pocket#14]
In dem neuen json werden noch Funktionen verwendet, die die Flutter lib nicht unterstützt. 
![grafik](https://github.com/Konradrundfunk/50ohm-pocket/assets/33392939/4ca47543-ccf9-41d7-a433-d930cac9d83e)

**Comment by thehilde** [comment]
Ist das noch aktuell? Auch hier könnte man sich mit RegExp(r'\\qty\[per-mode=symbol]\{([^}]*)\}\{([^}]*)\}'); auf die Suche machen. Allerdings haben die Daten das nur noch in der alten? Quetions.json.

**Comment by Konradrundfunk** [comment]
@myzinsky hat das glaube ich schon direkt in den Json files gefixed. Sollte daher geschlossen werden. Danke für den Hinweis.
