### ISSUE TITLE
lambda wird in Fragen nicht richtig gerendert

### ISSUE THREAD

**Issue by DO6FP** [DARC-e-V/50ohm-pocket#28]
Beispiele:
EB305 NB302

**Comment by myzinsky** [comment]
Hallo,

der Fehler ist bekannt und wurde bereits behoben. Beim nächsten Update der App sollte das Problem dann verschwinden.

vy73 de DL9MJ, Matthias

--

Prof. Dr. Matthias Jung (DL9MJ)

Ehrenamtliches Adminteam DARC-App
Deutscher Amateur-Radio-Club e. V.
Lindenallee 4
34225 Baunatal
Tel.: (05 61) 9 49 88-0
Fax:  (05 61) 9 49 88-50
E-Mail: ***@***.***
Web: [1] https://www.darc.de
Vereinsregister Kassel, VR 1314

> Am Samstag, 3. Februar 2024 um 14:59:36, schrieb DARC-e-V/50ohm-pocket :
>
> Beispiele:
> EB305 NB302
> —
> Reply to this email directly, [2] view it on GitHub, or [3] unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID:

[1] https://www.darc.de
[2] https://github.com/DARC-e-V/50ohm-pocket/issues/28
