### ISSUE TITLE
EB 409 enthält falsche Abbildung

### ISSUE THREAD

**Issue by fynnshark** [DARC-e-V/50ohm-pocket#30]
Bei EB 409 steht in der Abbildung, dass ein Segment 3s entspricht (3s/Div). In der Originalabbildung im PDF sind es 3µs/Div.
![photo_2024-02-14_23-20-07](https://github.com/DARC-e-V/50ohm-pocket/assets/160077186/30fb2ba6-236b-45b4-bb6b-c775210db8bb)

**Comment by myzinsky** [comment]
Fehler ist schon bekannt und wurde im Bildgenerator Gefixed.
