### ISSUE TITLE
Fehlerhafte Formel für SWR in Formelsammlung

### ISSUE THREAD

**Issue by boal** [DARC-e-V/50ohm-pocket#58]
In der Formelsammlung unter folgendem Link  ist die Formel für die SWR fehlerhaft.

Im Divisor sollte die rücklaufenden Leistung stehen. 

Siehe Markierung im Screenshot.

![image](https://github.com/user-attachments/assets/d2396e07-c394-44c5-85f2-37e502a0d604)

https://github.com/DARC-e-V/50ohm-pocket/blob/main/assets/pdf/Formelsammlung.pdf

**Comment by myzinsky** [comment]
Der Fehler ist bereits bekannt und im neuen Hilfsmitteldokument behoben, welches durch #56 hinzugefügt wird.
